version: '3'
services:
  rest:
    build: ./Server/REST
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - overlay
    depends_on:
      - db_server

  authapp:
    build: ./Server/AUTHAPP
    ports:
      - "8080"
    networks:
      - overlay
    depends_on:
      - redis

  webapp:
    build: ./Server/WEBAPP
    ports:
      - "8081"
    networks:
      - overlay
    depends_on:
      - redis

  socketclient:
    build: ./Server/SOCKETCLIENT
    ports:
      - "8083"
    networks:
      - overlay

  db_server:
    build: ./BDD-CLOUD/db_server
    ports:
      - "3000"
    depends_on:
      - mongo
    networks:
      - overlay

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017"
    networks:
      - overlay

  reco:
    restart: always
    build: ./recommandation
    ports:
      - "8000"
    depends_on:
      - db_server
    networks:
      - overlay

  redis:
    restart: always
    image: redis
    ports:
      - "6379"
    networks:
      - overlay

networks:
  overlay:
