version: "2"
services:

  db_server:
    container_name: db_server
    restart: always
    build: ./db_server
    ports:
      - "3000"
    depends_on:
      - mongo
      - mysql

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongodata:/data/db
    ports:
      - "27017:27017"

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306" 
    volumes:
      - ./dump/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: NightAdvisor
      MYSQL_USER: root
      MYSQL_PASSWORD: password


